name: riverine
description: 玩安卓移动端
homepage: git@github.com:wireflex9/riverine.git
publish_to: none
version: 1.0.0+1

environment:
  sdk: '^3.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  get: ^4.6.5
  get_storage: ^2.1.1
  dio: ^5.1.2
  flutter_screenutil: ^5.8.1
  flutter_easyloading: ^3.0.5
  flutter_easyrefresh: 2.2.1
  extended_image: ^8.0.1
  wechat_assets_picker: ^8.5.0
  wechat_camera_picker: ^3.8.0
  visibility_detector: 0.2.2
  asset_cache: 1.0.0+1
  path_provider: 2.0.9
  flutter_keyboard_visibility: ^5.4.0
  permission_handler: 10.2.0
  flutter_image_compress: 1.1.3
  rxdart: 0.27.3
  lottie: 1.3.0
  sprintf: 6.0.0
  decimal: 2.1.0
  scan: 1.6.0
  flutter_svg: ^2.0.5
  url_launcher: 6.0.20
  flutter_form_builder: ^9.0.0
  form_builder_validators: ^9.0.0
  firebase_storage: ^11.2.0
  firebase_core: ^2.12.0

dev_dependencies:
  lints: 1.0.1
  dio_http_formatter: ^3.1.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/lottie/
    - assets/images/svg/
    - assets/images/common/
